### ISSUE TITLE
在surface pro 4上，弹出的图片显示窗体定位有问题

### ISSUE THREAD

**Issue by KangKai1982** [alchen/DTCP#2]
点击比较大的图片，弹出的窗体经常定位在屏幕显示范围之外。

**Comment by alchen** [comment]
收到。没有那台机器，不过我试着研究看看。有外接、双、三显示器吗？

**Comment by KangKai1982** [comment]
没有外接

**Comment by alchen** [comment]
来的正好，试试这个 https://github.com/alchen/DTCP/releases/tag/v0.4.17

**Comment by KangKai1982** [comment]
yes！这次没问题了！非常感谢！

**Comment by alchen** [comment]
谢谢您帮忙测试 : )
